package com.javikx2.klondike.model;

public enum BoardState {
    WAITING_FOR_MOVE,
    MOVING_FROM_STOCK_TO_WASTE,
    MOVING_FROM_WASTE_TO_STOCK,
    MOVING_FROM_WASTE_TO_FOUNDATION,
    MOVING_FROM_WASTE_TO_TABLEAUPILE,
    MOVING_FROM_TABLEAUPILE_TO_FOUNDATION,
    MOVING_FROM_TABLEAUPILE_TO_TABLEAUPILE,
    MOVING_FROM_FOUNDATION_TO_TABLEAUPILE,
    FACING_UP_CARDS,
    CHECKING_WIN,
    GAME_OVER;
}

